name = "Buddy Worldcraft"
author = "Hawk"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "294dc3bc02f5aa06369b9239d6e9ff8bb2af5787a842984cb6316a4c1b46d1c1"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
