name = "Buddy Worldcraft"
author = "Hawk"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ebf2cf0fc487bdb8a1a6ab30a84ed29da0ae343d91f8de516a745d484b9cd0b"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
