name = "Buddy Worldcraft"
author = "Hawk"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7198ab17cdd7e8e2f9fd763248471c692fb4d2d69a3d195de35f6445e17dfdca"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
