name = "Buddy Worldcraft"
author = "Hawk"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe6b79f72b624a7fda950ac8073be2870a977d9de52d22aefcc3b3b07125ac68"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
